"""empty message

Revision ID: 597aa80038b6
Revises: 
Create Date: 2020-08-28 05:13:50.462971

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '597aa80038b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_characters_char_id'), 'characters', ['char_id'])
    op.create_index(op.f('ix_characters_name'), 'characters', ['name'])
    op.drop_index('id', table_name='characters')
    op.drop_index('name', table_name='characters')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'characters',
        'A table for characters names',
        existing_comment=None,
        schema=None
    )
    op.create_index('name', 'characters', ['name'], unique=True)
    op.create_index('id', 'characters', ['char_id'], unique=True)
    op.drop_index(op.f('ix_characters_name'), table_name='characters')
    op.drop_index(op.f('ix_characters_char_id'), table_name='characters')
    op.create_table_comment(
        'character_moves',
        'A table for the moves of the characters of TEKKEN 7',
        existing_comment=None,
        schema=None
    )
    op.alter_column('character_moves', 'character',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=32),
               nullable=False)
    # ### end Alembic commands ###
